title: <p align="center"> Sanchita </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://github.com/sanchita238">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  <br>
  </p>



theme: jekyll-theme-minimal
